spring:
  application:
    name: korobki-calculator

  datasource:
    url: jdbc:postgresql://localhost:5432/korobki
    username: postgres
    password: 4meonl
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET:very_long_secret_key_for_jwt_at_least_256_bits}
  expiration: 28800000

app:
  pricing:
    manufacturing-cost: 5.0
    markup-min: 30.0
    markup-multiplier: 3.0
    tax-rate: 0.11
    discount-steps:
      "до 9": 7.0
      "10–49": 0.0
      "50–199": -2.0
      "200–499": -4.0
      "500–699": -6.0
      "700–1499": -8.0
      "от 1500": -10.0
    x3-coefficients:
      "до 9": 1.0
      "10–49": 1.0
      "50–199": 0.95
      "200–499": 0.90
      "500–699": 0.85
      "700–1499": 0.80
      "от 1500": 0.75
    knife-price-per-mm: 3.0
    knife-base-cost: 500.0